In [10]:
#indexing 索引 
import torch 
a=torch.rand(2,3,4,5)
print(a)
print(a[0].shape)
print(a[0,0].shape)
print(a[0,0,3,4])

tensor([[[[0.3424, 0.4735, 0.6019, 0.2183, 0.7053],
          [0.1255, 0.4527, 0.4383, 0.8871, 0.4249],
          [0.9922, 0.4000, 0.6821, 0.1389, 0.6244],
          [0.9126, 0.3076, 0.5213, 0.8164, 0.7986]],

         [[0.5591, 0.4268, 0.0326, 0.6768, 0.0596],
          [0.3082, 0.4028, 0.3257, 0.5144, 0.0874],
          [0.2007, 0.4218, 0.8566, 0.6315, 0.1378],
          [0.2933, 0.6671, 0.2282, 0.7907, 0.6720]],

         [[0.1245, 0.2437, 0.9389, 0.7019, 0.0027],
          [0.4857, 0.7253, 0.7568, 0.7947, 0.5129],
          [0.7756, 0.2221, 0.2845, 0.6171, 0.2042],
          [0.4540, 0.5131, 0.2742, 0.6717, 0.3575]]],


        [[[0.6552, 0.9445, 0.5094, 0.0252, 0.9753],
          [0.8892, 0.7981, 0.6623, 0.6932, 0.2726],
          [0.8407, 0.5611, 0.8577, 0.4815, 0.3195],
          [0.8278, 0.5810, 0.8179, 0.4836, 0.2879]],

         [[0.6208, 0.5435, 0.7257, 0.8891, 0.7865],
          [0.5563, 0.1215, 0.3791, 0.1386, 0.0867],
          [0.2981, 0.2562, 0.3165, 0.4309, 0.5028],
  

In [34]:
# ：的应用
import torch
a=torch.rand(3,3,4,5) #3张照片 rgb通道 每个通道4*5
#print(a)
print(a.shape) #打印a的维度 ，四个数，四个维度，每一维度下的数据
print(a[:2].shape) #0->2 [0,2) 将第1张和第二张照片的格式打印出来
print(a[:2,:1,:,:].shape) #第一 第二张照片的 r通道 每个像素点 

# ：再数的后面
print(a[:2,1:,:,:].shape) #第一和第二张照片 的g、b通道每个像素点
print(a[:2,-3:,:,:].shape) #第一和第二张照片，rgb三个通道的每个像素点

torch.Size([3, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([2, 1, 4, 5])
torch.Size([2, 2, 4, 5])
torch.Size([2, 3, 4, 5])


In [37]:
#：隔行采样
import torch
a=torch.rand(3,3,4,5)
print(a[:,:,0:4:2,0:5:2].shape)#取不到最后一个元素

torch.Size([3, 3, 2, 3])


In [39]:
import torch
a=torch.rand(3,3,4,5)
print(a[:,:,::2,::2].shape)

torch.Size([3, 3, 2, 3])


In [44]:
#再特定的维度上的索引进行操作
import torch
a=torch.rand(3,3,4,5)
print(a)
#a.shape
print(a.index_select(0,torch.tensor([0,2])).shape) #对0索引（照片）上第1张和第3张照片 像素点输出
print(a.index_select(0,torch.tensor([0,2])))

tensor([[[[0.9211, 0.1069, 0.8624, 0.6023, 0.5854],
          [0.7664, 0.4168, 0.1787, 0.3211, 0.4585],
          [0.7625, 0.8636, 0.5052, 0.8633, 0.6810],
          [0.5946, 0.6573, 0.5736, 0.7085, 0.4859]],

         [[0.1194, 0.6309, 0.3706, 0.9133, 0.5511],
          [0.0408, 0.4569, 0.7792, 0.6566, 0.1235],
          [0.4751, 0.5349, 0.1684, 0.4220, 0.9295],
          [0.7614, 0.4366, 0.7831, 0.7763, 0.7967]],

         [[0.4837, 0.5443, 0.2332, 0.6085, 0.3175],
          [0.0057, 0.9752, 0.4683, 0.3870, 0.4079],
          [0.9600, 0.3321, 0.8518, 0.3829, 0.3492],
          [0.1667, 0.1457, 0.9300, 0.3683, 0.7379]]],


        [[[0.7915, 0.0786, 0.4925, 0.4149, 0.6207],
          [0.6696, 0.0580, 0.0304, 0.0028, 0.3159],
          [0.1133, 0.6083, 0.4585, 0.3082, 0.7666],
          [0.5616, 0.1516, 0.3055, 0.5391, 0.1170]],

         [[0.1290, 0.7573, 0.3734, 0.0590, 0.0374],
          [0.0683, 0.4859, 0.9572, 0.5584, 0.9996],
          [0.9514, 0.3307, 0.4842, 0.4336, 0.5905],
  

In [45]:
#再特定的维度上的索引进行操作 rgb通道上的操作
import torch
a=torch.rand(3,3,4,5)
print(a)
#a.shape
print(a.index_select(1,torch.tensor([0,1])).shape) #对1索引（通道）中的 RG通道的像素点进行输出 
print(a.index_select(1,torch.tensor([0,1])))

tensor([[[[0.9010, 0.7066, 0.8184, 0.7270, 0.0368],
          [0.9708, 0.4154, 0.4453, 0.2924, 0.1611],
          [0.2561, 0.2102, 0.9114, 0.5110, 0.7310],
          [0.7998, 0.1347, 0.2221, 0.9285, 0.2046]],

         [[0.6414, 0.9493, 0.0545, 0.6276, 0.3273],
          [0.9776, 0.3427, 0.1149, 0.5322, 0.4446],
          [0.0370, 0.0376, 0.1378, 0.6482, 0.9664],
          [0.0157, 0.1332, 0.1571, 0.4261, 0.9942]],

         [[0.3068, 0.5753, 0.9197, 0.1654, 0.1268],
          [0.6710, 0.9110, 0.0536, 0.2481, 0.4249],
          [0.8815, 0.7263, 0.4260, 0.2051, 0.5553],
          [0.2941, 0.1690, 0.9457, 0.0690, 0.8270]]],


        [[[0.0766, 0.5478, 0.9372, 0.9404, 0.3012],
          [0.1457, 0.0262, 0.1690, 0.4163, 0.0014],
          [0.1478, 0.0787, 0.3179, 0.5767, 0.3584],
          [0.7140, 0.2375, 0.6672, 0.1091, 0.2902]],

         [[0.1083, 0.8147, 0.7892, 0.9540, 0.1188],
          [0.9242, 0.4351, 0.0726, 0.8635, 0.5887],
          [0.6358, 0.3889, 0.3689, 0.5680, 0.5750],
  

In [50]:
#再特定的维度上的索引进行操作 照片高度上的操作
import torch
a=torch.rand(3,3,4,5)
print(a)
#a.shape
print(a.index_select(2,torch.arange(4)).shape)#对2索引（照片）中的h进行操作 输出【0,1,2,3】
print(a.index_select(2,torch.arange(4)))

tensor([[[[0.0482, 0.4942, 0.2148, 0.9900, 0.9291],
          [0.9059, 0.4511, 0.9516, 0.7843, 0.8721],
          [0.5459, 0.1867, 0.8638, 0.6109, 0.3417],
          [0.3552, 0.9712, 0.3355, 0.3048, 0.9760]],

         [[0.6485, 0.9483, 0.1959, 0.3950, 0.0749],
          [0.2735, 0.6803, 0.5610, 0.8092, 0.5967],
          [0.9377, 0.4324, 0.2186, 0.0674, 0.5293],
          [0.8511, 0.8593, 0.1028, 0.8399, 0.6873]],

         [[0.2891, 0.2118, 0.1768, 0.2849, 0.0621],
          [0.6276, 0.0717, 0.5615, 0.3618, 0.5038],
          [0.8268, 0.7681, 0.3475, 0.1701, 0.7960],
          [0.2753, 0.7825, 0.6214, 0.2128, 0.8179]]],


        [[[0.6885, 0.5383, 0.5018, 0.9131, 0.2672],
          [0.8664, 0.9225, 0.1120, 0.4311, 0.7053],
          [0.5622, 0.2483, 0.8759, 0.3162, 0.9049],
          [0.0696, 0.0886, 0.3004, 0.1656, 0.0768]],

         [[0.5486, 0.7477, 0.5232, 0.9836, 0.5793],
          [0.1745, 0.7489, 0.2052, 0.1111, 0.1301],
          [0.7345, 0.7742, 0.4158, 0.8105, 0.1391],
  

In [51]:
#...省略号的使用
import torch
a=torch.rand(3,3,4,5)
a[...].shape

torch.Size([3, 3, 4, 5])

In [52]:
a[0,...].shape

torch.Size([3, 4, 5])

In [53]:
a[:,1,...].shape #输出3张照片的每个g通道下的像素点

torch.Size([3, 4, 5])

In [58]:
print(a[...,:2]) #输出3张照片每个rgb通道下的前两列
a[...,:2].shape

tensor([[[[0.8827, 0.4942],
          [0.6518, 0.6290],
          [0.6273, 0.0482],
          [0.4830, 0.1502]],

         [[0.3208, 0.5340],
          [0.6885, 0.5448],
          [0.2054, 0.3180],
          [0.7883, 0.4447]],

         [[0.9093, 0.6356],
          [0.6564, 0.1511],
          [0.1276, 0.8106],
          [0.5326, 0.3146]]],


        [[[0.3807, 0.7674],
          [0.6625, 0.0650],
          [0.2132, 0.2824],
          [0.8760, 0.5509]],

         [[0.6789, 0.9615],
          [0.7288, 0.1455],
          [0.6975, 0.4480],
          [0.8070, 0.4066]],

         [[0.2874, 0.7763],
          [0.2734, 0.3170],
          [0.7325, 0.4133],
          [0.8048, 0.7201]]],


        [[[0.4757, 0.2549],
          [0.8166, 0.6470],
          [0.9921, 0.5707],
          [0.5467, 0.8751]],

         [[0.7646, 0.0929],
          [0.0206, 0.6151],
          [0.2048, 0.9838],
          [0.0683, 0.1808]],

         [[0.6396, 0.3944],
          [0.4109, 0.0857],
          [0.1477, 0.2470],


torch.Size([3, 3, 4, 2])

In [64]:
#select by musk 选出tensor中某个大于或者小于某个阈值的值
import torch
x=torch.rand(4,4)
print(x)

mask=x.ge(0.5)
print(mask)

Y=torch.masked_select(x,mask)
print(Y)

Y.shape

tensor([[0.1272, 0.9880, 0.4599, 0.8011],
        [0.1580, 0.7613, 0.3645, 0.2149],
        [0.4236, 0.8478, 0.7280, 0.9462],
        [0.5268, 0.3488, 0.8410, 0.7373]])
tensor([[False,  True, False,  True],
        [False,  True, False, False],
        [False,  True,  True,  True],
        [ True, False,  True,  True]])
tensor([0.9880, 0.8011, 0.7613, 0.8478, 0.7280, 0.9462, 0.5268, 0.8410, 0.7373])


torch.Size([9])

In [67]:
#选出索引为n此时的tensor数据是什么 打平取索引下的数据
import torch
a=torch.tensor([[3,4,5],[7,8,9]])
torch.take(a,torch.tensor([0,2,5]))

tensor([3, 5, 9])