In [14]:
#将numpy数据转到tensor中
import torch
import numpy as np
a=np.array([2,3.3])
b=torch.from_numpy(a)
print(a,"\n",b,"\n")

c=np.ones([2,3])
d=torch.from_numpy(c)
print(c,"\n",d)

[2.  3.3] 
 tensor([2.0000, 3.3000], dtype=torch.float64) 

[[1. 1. 1.]
 [1. 1. 1.]] 
 tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [24]:
#tensor 与Tensor 
import torch
a=torch.tensor([2,3.2])
print(a)

b=torch.FloatTensor([2,3.2])
print(b)

c=torch.FloatTensor(2,3)#生成两行三列的tensor
print(c)

d=torch.tensor([[2.0,3.2],
                 [1.8,2.9]])
print(d)

tensor([2.0000, 3.2000])
tensor([2.0000, 3.2000])
tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [1.6244e-07, 1.0256e-08, 1.2972e-11]])
tensor([[2.0000, 3.2000],
        [1.8000, 2.9000]])


In [36]:
#利用Tensor生成未初始化的数据
import torch
a=torch.empty(1)
b=torch.empty(2,3)
print(a,"\n",b)

c=torch.Tensor(2,3)
d=torch.IntTensor(2,3)
e=torch.FloatTensor(3,3)
print(c)
print(d)
print(e)

tensor([nan]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[         0,          0, 1852990827],
        [ 875457637,  842019889,  761541986]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [40]:
#调整数据类型的默认设置
import torch
a=torch.tensor([1.2,2,3]).type()
print(a)
torch.set_default_tensor_type(torch.DoubleTensor)
b=torch.tensor([1.2,2,3]).type()
print(b)

torch.FloatTensor
torch.DoubleTensor


In [44]:
#rand rand_like randint 应用
import torch
a=torch.rand(3,3)
print(a)
b=torch.rand_like(a)
print(b)
c=torch.randint(1,10,[3,3]) #【1,10） 3*3的tensor
print(c)

tensor([[0.6076, 0.2094, 0.5947],
        [0.4974, 0.5528, 0.1686],
        [0.9392, 0.6372, 0.6871]])
tensor([[0.1318, 0.4471, 0.7802],
        [0.7070, 0.5640, 0.9221],
        [0.9406, 0.9927, 0.0893]])
tensor([[3, 8, 3],
        [5, 8, 2],
        [8, 7, 4]])


In [48]:
#full
import torch
a=torch.full([2,3],8)
print(a)

b=torch.full([],7)
c=torch.full([1],7)

print(b)
print(c)

tensor([[8, 8, 8],
        [8, 8, 8]])
torch.LongTensor
tensor([7])


In [52]:
#arange
import torch
print(torch.arange(0,10)) #[0,10) 默认以1递增
print(torch.arange(0,10,2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [59]:
#linspace
import torch
print(torch.linspace(0,10,steps=5)) #（末-初）/（step-1）
print(torch.linspace(0,10,steps=10)) #（末-初）/（step-1）
print(torch.linspace(0,10,steps=11)) #（末-初）/（step-1）
#logspace

print(torch.logspace(0,-1,steps=10))

print(torch.logspace(0,1,steps=10))

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])
tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])


In [68]:
#ones zeros eye
import torch
print(torch.ones(3,3))
a=torch.zeros(3,3)
print(a)
print(torch.eye(3,3))
print(torch.eye(3,4))

#like

print(torch.ones_like(a))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [72]:
#randperm
import torch
torch.randperm(10)#0-9

tensor([4, 9, 5, 3, 1, 2, 6, 8, 0, 7])

In [82]:
#randperm 应用
import torch
a=torch.rand(2,3)
b=torch.rand(2,2)
idx=torch.randperm(2)
print(a)
print(b)
print(idx)
print(a[idx])
print(b[idx])

tensor([[0.2352, 0.4276, 0.6322],
        [0.3318, 0.7633, 0.5072]])
tensor([[0.1767, 0.7503],
        [0.8307, 0.9706]])
tensor([1, 0])
tensor([[0.3318, 0.7633, 0.5072],
        [0.2352, 0.4276, 0.6322]])
tensor([[0.8307, 0.9706],
        [0.1767, 0.7503]])
