In [1]:
import torch
from torch.nn import functional as F
x=torch.randn(1,10)
x

tensor([[-0.0762,  0.2622, -0.2070,  0.4603,  0.7033,  0.0299, -2.5732, -1.6656,
          1.2812, -1.3315]])

In [2]:
w=torch.randn(1,10,requires_grad=True)
w

tensor([[ 0.0103,  0.0825,  0.2907,  0.7920,  0.5531, -0.0518,  0.4469, -0.4265,
         -1.8899, -0.6755]], requires_grad=True)

In [3]:
o=torch.sigmoid(x@w.t())
o

tensor([[0.2229]], grad_fn=<SigmoidBackward>)

In [4]:
o.shape

torch.Size([1, 1])

In [5]:
loss=F.mse_loss(torch.ones(1,1),o)

In [6]:
loss.shape

torch.Size([])

In [7]:
loss.backward()

In [8]:
w.grad

tensor([[ 0.0205, -0.0706,  0.0557, -0.1239, -0.1893, -0.0081,  0.6927,  0.4484,
         -0.3449,  0.3585]])