In [2]:
#基本运算
import torch
a=torch.rand(3,4)
b=torch.rand(4)
print(a+b) #b会自动复制（broadcast）第一行3次
print(torch.add(a,b)) #加法

tensor([[0.2855, 0.7372, 1.2909, 1.2220],
        [1.0423, 0.6461, 1.4780, 0.8315],
        [0.9093, 0.9801, 0.8777, 0.7838]])
tensor([[0.2855, 0.7372, 1.2909, 1.2220],
        [1.0423, 0.6461, 1.4780, 0.8315],
        [0.9093, 0.9801, 0.8777, 0.7838]])


In [3]:
#减法
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

In [4]:
#乘法
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [11]:
#除法d
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(True)

In [16]:
#矩阵之间的乘法计算
import torch
a=torch.full([2,2],3.)
print(a)
b=torch.ones(2,2)
print(b)
print(torch.mm(a,b))
print(torch.matmul(a,b))
print(a@b)

tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
tensor([[6., 6.],
        [6., 6.]])
tensor([[6., 6.],
        [6., 6.]])


In [21]:
# example 神经网络线性层降低维度(4,784)->(4,512)
import torch
a=torch.rand(4,784)
x=torch.rand(4,784)
w=torch.rand(512,784)
torch.matmul(x,w.t()).shape

torch.Size([4, 512])

In [23]:
#多维tensor相乘
import torch
a=torch.rand(4,3,5,4)
b=torch.rand(4,3,4,6)
torch.matmul(a,b).shape

torch.Size([4, 3, 5, 6])

In [24]:
a=torch.rand(4,3,28,64)
b=torch.rand(4,1,64,32)
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [25]:
a=torch.rand(4,4,28,64)
b=torch.rand(4,64,32)
torch.matmul(a,b).shape

torch.Size([4, 4, 28, 32])

In [26]:
#power
import torch
a=torch.full([2,2],3.0)
a**2

tensor([[9., 9.],
        [9., 9.]])

In [29]:
b=a.pow(2)
b

tensor([[9., 9.],
        [9., 9.]])

In [30]:
b**(0.5)

tensor([[3., 3.],
        [3., 3.]])

In [31]:
b.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [38]:
#exp log
import torch
a=torch.exp(torch.tensor([1.0]))
print(a)

tensor([2.7183])


tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [40]:
b=torch.exp(torch.ones(2,2))
b

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [41]:
torch.log(b)

tensor([[1., 1.],
        [1., 1.]])

In [42]:
#近似值操作
import torch
a=torch.tensor(3.14)

In [43]:
a.floor()#向下取整

tensor(3.)

In [45]:
a.ceil()#向上取整

tensor(4.)

In [46]:
a.trunc() #取整数部分

tensor(3.)

In [47]:
a.frac()#取小数部分

tensor(0.1400)

In [48]:
a.round()#四舍五入

tensor(3.)

In [49]:
#clamp 裁剪同化
import torch
a=torch.rand(2,3)*10
print(a)

tensor([[3.2089, 9.2346, 3.7801],
        [6.8394, 1.3372, 4.9550]])


In [50]:
a.max()#最大

tensor(9.2346)

In [51]:
a.min()#最小

tensor(1.3372)

In [52]:
a.median() #中间

tensor(3.7801)

In [53]:
a.clamp(6)#比6小的数全部变成6

tensor([[6.0000, 9.2346, 6.0000],
        [6.8394, 6.0000, 6.0000]])

In [54]:
a.clamp(3,6) #比3小变成3 比6大变成6

tensor([[3.2089, 6.0000, 3.7801],
        [6.0000, 3.0000, 4.9550]])