In [5]:
#view 对原有的维度信息重排
import torch
a=torch.tensor([[1,2],[2,3],[3,4]])
print(a)
print(a.shape)
a.view(6)#一个维度，该维度下的size长度为6

tensor([[1, 2],
        [2, 3],
        [3, 4]])
torch.Size([3, 2])


tensor([1, 2, 2, 3, 3, 4])

In [13]:
import torch
a=torch.rand(2,1,4,5)
print(a)
print(a.shape)
print("\n")
a=a.view(2,4*5)
print(a)
print(a.shape)

tensor([[[[0.2174, 0.2867, 0.3068, 0.5994, 0.9521],
          [0.6173, 0.6100, 0.1303, 0.4854, 0.6735],
          [0.1805, 0.5019, 0.1227, 0.4817, 0.1510],
          [0.4710, 0.7513, 0.4348, 0.6821, 0.9308]]],


        [[[0.7852, 0.6164, 0.9093, 0.5017, 0.0066],
          [0.9406, 0.1054, 0.9700, 0.8031, 0.1847],
          [0.9452, 0.9972, 0.3470, 0.7698, 0.4635],
          [0.7816, 0.1602, 0.3575, 0.0869, 0.0405]]]])
torch.Size([2, 1, 4, 5])


tensor([[0.2174, 0.2867, 0.3068, 0.5994, 0.9521, 0.6173, 0.6100, 0.1303, 0.4854,
         0.6735, 0.1805, 0.5019, 0.1227, 0.4817, 0.1510, 0.4710, 0.7513, 0.4348,
         0.6821, 0.9308],
        [0.7852, 0.6164, 0.9093, 0.5017, 0.0066, 0.9406, 0.1054, 0.9700, 0.8031,
         0.1847, 0.9452, 0.9972, 0.3470, 0.7698, 0.4635, 0.7816, 0.1602, 0.3575,
         0.0869, 0.0405]])
torch.Size([2, 20])


In [14]:
#添加维度信息 unsqueeze
import torch
a=torch.rand(3,3,4,5)
print(a.shape)

torch.Size([3, 3, 4, 5])

In [15]:
a.unsqueeze(0).shape #正数放前面，负数放后面

torch.Size([1, 3, 3, 4, 5])

In [16]:
a.unsqueeze(-1).shape

torch.Size([3, 3, 4, 5, 1])

In [17]:
a.unsqueeze(4).shape

torch.Size([3, 3, 4, 5, 1])

In [18]:
a.unsqueeze(-4).shape

torch.Size([3, 1, 3, 4, 5])

In [19]:
a.unsqueeze(-2).shape

torch.Size([3, 3, 4, 1, 5])

In [22]:
#example
import torch
b=torch.rand(3)
f=torch.rand(3,3,4,5)
b=b.unsqueeze(0).unsqueeze(2).unsqueeze(3)
b.shape

torch.Size([1, 3, 1, 1])

In [33]:
#挤压维度 
import torch
a=torch.rand(1,3,2,1)
print(a)
print(a.squeeze())
a.squeeze().shape

tensor([[[[0.1000],
          [0.3911]],

         [[0.2977],
          [0.0347]],

         [[0.6076],
          [0.0851]]]])
tensor([[0.1000, 0.3911],
        [0.2977, 0.0347],
        [0.6076, 0.0851]])


torch.Size([3, 2])

In [40]:
#expend 维度里的size扩充
import torch
a=torch.rand(2,3,4,5)
print(a,"\n")
b=torch.rand(1,3,1,1)
print(b)
print(b.expand(2,3,4,5))
b.expand(2,3,4,5).shape

print(b)
print(b.expand(-1,3,-1,-1)) #-1指示维度不发生变化
b.expand(-1,3,-1,-1).shape

tensor([[[[0.9692, 0.2110, 0.3410, 0.4367, 0.7768],
          [0.1653, 0.4328, 0.5366, 0.2239, 0.3358],
          [0.5937, 0.4381, 0.7164, 0.5870, 0.9485],
          [0.8073, 0.7881, 0.1023, 0.7416, 0.1231]],

         [[0.3362, 0.3258, 0.3519, 0.5405, 0.8766],
          [0.3348, 0.7855, 0.1366, 0.7468, 0.5281],
          [0.4714, 0.9728, 0.0383, 0.8488, 0.1043],
          [0.4538, 0.7432, 0.3904, 0.8022, 0.1137]],

         [[0.8616, 0.3477, 0.7084, 0.8183, 0.7124],
          [0.3954, 0.0538, 0.0724, 0.2695, 0.4386],
          [0.2058, 0.1529, 0.5361, 0.9729, 0.0283],
          [0.7823, 0.1923, 0.4459, 0.2971, 0.5117]]],


        [[[0.7962, 0.7621, 0.8383, 0.5848, 0.3256],
          [0.2087, 0.9572, 0.7487, 0.9812, 0.2814],
          [0.5913, 0.5653, 0.3399, 0.4649, 0.9601],
          [0.3188, 0.1323, 0.0739, 0.8193, 0.8718]],

         [[0.2484, 0.8759, 0.9424, 0.6758, 0.4608],
          [0.7131, 0.1476, 0.3204, 0.9981, 0.1700],
          [0.4464, 0.7068, 0.9979, 0.9567, 0.9814],
  

torch.Size([1, 3, 1, 1])

In [44]:
#repeat 维度相乘为后面的
import torch
a=torch.rand(1,2,2,4)
print(a)
b=a.repeat(4,1,1,1)
print(b)

b.shape

tensor([[[[0.6004, 0.1467, 0.6945, 0.7373],
          [0.6998, 0.8153, 0.4561, 0.1832]],

         [[0.2132, 0.0564, 0.8540, 0.9952],
          [0.1038, 0.1751, 0.7577, 0.2783]]]])
tensor([[[[0.6004, 0.1467, 0.6945, 0.7373],
          [0.6998, 0.8153, 0.4561, 0.1832]],

         [[0.2132, 0.0564, 0.8540, 0.9952],
          [0.1038, 0.1751, 0.7577, 0.2783]]],


        [[[0.6004, 0.1467, 0.6945, 0.7373],
          [0.6998, 0.8153, 0.4561, 0.1832]],

         [[0.2132, 0.0564, 0.8540, 0.9952],
          [0.1038, 0.1751, 0.7577, 0.2783]]],


        [[[0.6004, 0.1467, 0.6945, 0.7373],
          [0.6998, 0.8153, 0.4561, 0.1832]],

         [[0.2132, 0.0564, 0.8540, 0.9952],
          [0.1038, 0.1751, 0.7577, 0.2783]]],


        [[[0.6004, 0.1467, 0.6945, 0.7373],
          [0.6998, 0.8153, 0.4561, 0.1832]],

         [[0.2132, 0.0564, 0.8540, 0.9952],
          [0.1038, 0.1751, 0.7577, 0.2783]]]])


torch.Size([4, 2, 2, 4])

In [45]:
#矩阵的转置
import torch
a=torch.rand(2,2)
print(a)
b=a.t()
print(b)

tensor([[0.8759, 0.8730],
        [0.9429, 0.4904]])
tensor([[0.8759, 0.9429],
        [0.8730, 0.4904]])


In [47]:
#transpose 维度交换
import torch
a=torch.rand(4,3,2,5)
print(a.shape)
a1=a.transpose(1,3).contiguous().view(4,3*2*5).view(4,3,2,5)
a2=a.transpose(1,3).contiguous().view(4,3*2*5).view(4,5,2,3).transpose(1,3)

torch.all(torch.eq(a,a1))


torch.Size([4, 3, 2, 5])


tensor(False)

In [48]:
torch.all(torch.eq(a,a2))

tensor(True)

In [49]:
#permute 直接按索引指示维度重排
import torch
a=torch.rand(4,3,2,1)
print(a.shape)
b=a.permute(0,2,3,1)
b.shape

torch.Size([4, 3, 2, 1])


torch.Size([4, 2, 1, 3])