In [5]:
import torch #导出包
a=torch.randn(2,2,requires_grad=True)#随机矩阵2*2 梯度需要回传 http://www.imooc.com/article/282785
print(a)#打印a

tensor([[-1.5385, -0.4524],
        [ 0.2492, -1.5037]], requires_grad=True)


In [10]:
#gpu cpu 运行比较 通过矩阵相乘例子
# 导出torch time 包
import torch
import  time
#输出torch 版本号
print(torch.__version__)
#cuda 是否可用
print(torch.cuda.is_available())
# print('hello, world.')
a = torch.randn(10000, 1000) #维度二维 10000*1000 矩阵 张量
b = torch.randn(1000, 2000)
#测量当前时间 time包下的time（）函数
t0 = time.time()
#torch 包下的乘法函数 简写mm
#矩阵相乘有torch.mm和torch.matmul两个函数。其中前一个是针对二维矩阵，后一个是高维。
c1 = torch.matmul(a, b)
c2=torch.mm(a,b)
print(c1)
print(c2)
#再次测量当前时间
t1 = time.time()
# 再a当前设备环境下求时间差，norm计算张量c1的2 范数 
#L1范数[公式]：为x向量各个元素绝对值之和；
#L2范数[公式]：为x向量各个元素平方和的开方。
#s输出a计算的平台 时间差 c1矩阵的2范数 
print(a.device, t1 - t0, c1.norm(2))

#torch 的加载驱动是cuda
device = torch.device('cuda')
#a ，b 数据迁移到gpu上
a = a.to(device)
b = b.to(device)
#时间差计算（含初始化）
t0 = time.time()
c = torch.matmul(a, b)
t2 = time.time()
print(a.device, t2 - t0, c.norm(2))
#时间差计算不含初始化
t0 = time.time()
c = torch.matmul(a, b)
t2 = time.time()
print(a.device, t2 - t0, c.norm(2))




1.7.0+cpu
False
tensor([[  8.5406, -33.4901,  22.4228,  ...,  20.7483, -25.4220,  36.2472],
        [ -2.0632,  -4.3330,  -6.8543,  ...,  50.6221,   0.9619,   3.5539],
        [-21.2484,  46.4704, -20.6733,  ...,  19.9191,  29.4552, -51.5773],
        ...,
        [  9.7814, -16.6600, -16.3109,  ...,  10.4525,   7.9594,  21.2604],
        [-25.5473,   5.4510, -26.1965,  ...,  22.8937,  81.6671, -45.9704],
        [-19.9500,   1.0496, -25.0992,  ...,  62.3786, -55.3084,  37.6104]])
tensor([[  8.5406, -33.4901,  22.4228,  ...,  20.7483, -25.4220,  36.2472],
        [ -2.0632,  -4.3330,  -6.8543,  ...,  50.6221,   0.9619,   3.5539],
        [-21.2484,  46.4704, -20.6733,  ...,  19.9191,  29.4552, -51.5773],
        ...,
        [  9.7814, -16.6600, -16.3109,  ...,  10.4525,   7.9594,  21.2604],
        [-25.5473,   5.4510, -26.1965,  ...,  22.8937,  81.6671, -45.9704],
        [-19.9500,   1.0496, -25.0992,  ...,  62.3786, -55.3084,  37.6104]])
cpu 0.37100768089294434 tensor(140861.9844)


AssertionError: Torch not compiled with CUDA enabled

In [23]:
#计算梯度信息
#from  A   import   B 和import A两种方式的导入之后，
#在函数的使用上不同。前者的函数可以直接使用，而后者如果想使用A模块中的B函数时，需要使用"A.B"。
import  torch
from    torch import autograd

#x是维度1*1的张量 数据是1.
x = torch.tensor(1.)
print(x)
#y = torch.tensor(1)
#print(y)

#y=a^2 * x +bx+c
#类似设置超参数
a = torch.tensor(1., requires_grad=True)
b = torch.tensor(2., requires_grad=True)
c = torch.tensor(3., requires_grad=True)

y = a**2 * x + b * x + c
#a，b，c并没有相对的梯度信息
print('before:', a.grad, b.grad, c.grad)
#autograd包方法中grad（）函数 计算 y相对于abc的梯度。输出结果映射到grads中
grads = autograd.grad(y, [a, b, c])
print('after :', grads[0], grads[1], grads[2])


tensor(1.)
before: None None None
after : tensor(2.) tensor(1.) tensor(1.)
