In [1]:
#where 根据条件取值
import torch
cond=torch.tensor([[0.2,0.6],[0.52,0.21]])
a=torch.ones(2,2)
b=torch.zeros(2,2)

In [2]:
a

tensor([[1., 1.],
        [1., 1.]])

In [3]:
b

tensor([[0., 0.],
        [0., 0.]])

In [4]:
torch.where(cond>0.5,a,b) #cond>0.5，则取a的值，反之，取b的值

tensor([[0., 1.],
        [1., 0.]])

In [5]:
#gather 根据索引，返回当前表中索引下的数据
prob=torch.randn(4,10)
prob

tensor([[ 0.1337, -0.0178,  0.3801,  0.8936, -1.1834,  0.8309, -1.9054,  0.1271,
         -0.0213,  0.9316],
        [ 1.1484, -0.6181,  0.1286, -0.5846, -1.5910,  1.7089, -1.6684,  0.9827,
         -1.7316,  0.3281],
        [-0.1860, -0.5036,  0.6032, -0.7732, -1.3863,  0.0441,  1.3877,  1.6864,
         -1.5450,  1.0775],
        [-0.3077, -0.7647, -0.2238,  0.7246,  0.0525,  0.5213,  0.7277, -0.3629,
         -0.0824, -1.1100]])

In [6]:
idx=prob.topk(dim=1,k=3)
idx

torch.return_types.topk(
values=tensor([[0.9316, 0.8936, 0.8309],
        [1.7089, 1.1484, 0.9827],
        [1.6864, 1.3877, 1.0775],
        [0.7277, 0.7246, 0.5213]]),
indices=tensor([[9, 3, 5],
        [5, 0, 7],
        [7, 6, 9],
        [6, 3, 5]]))

In [7]:
idx=idx[1]
idx

tensor([[9, 3, 5],
        [5, 0, 7],
        [7, 6, 9],
        [6, 3, 5]])

In [9]:
laber=torch.arange(10)+100
laber

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [10]:
torch.gather(laber.expand(4,10),dim=1,index=idx) #再expend表中的第一维度中，找出索引等于idx的

tensor([[109, 103, 105],
        [105, 100, 107],
        [107, 106, 109],
        [106, 103, 105]])