In [5]:
# cat  拼接 拼接的tensor有一个维度不同，其余维度相同 维度相加
import torch
a=torch.rand(4,32,8) #四个班级，一个班级32名学生.一名学生8门课成绩
#print(a)
b=torch.rand(5,32,8)
torch.cat([a,b],dim=0).shape #0维度上（第一个维度）拼接，九个班级.一个班级32名学生，一名学生8门课成绩

torch.Size([9, 32, 8])

In [7]:
#example 2张照片 三个通道  扩展成4个通道
import torch
a=torch.rand(2,3,4,5)
b=torch.rand(2,1,4,5)
print(a)
print(b)
c=torch.cat([a,b],dim=1)
print(c)

tensor([[[[0.7317, 0.3687, 0.9829, 0.2006, 0.4505],
          [0.4897, 0.7859, 0.1842, 0.0942, 0.7722],
          [0.6607, 0.3240, 0.4250, 0.7176, 0.4209],
          [0.0282, 0.5599, 0.0557, 0.3658, 0.6063]],

         [[0.3705, 0.1936, 0.6427, 0.1076, 0.1678],
          [0.3097, 0.1285, 0.7137, 0.7207, 0.6830],
          [0.8009, 0.5123, 0.5033, 0.7008, 0.4556],
          [0.7560, 0.3277, 0.0960, 0.9722, 0.2510]],

         [[0.8863, 0.3911, 0.7523, 0.6070, 0.7026],
          [0.0113, 0.8283, 0.4579, 0.9996, 0.1922],
          [0.2386, 0.5931, 0.4828, 0.7853, 0.8355],
          [0.1434, 0.8187, 0.8965, 0.9496, 0.2348]]],


        [[[0.4810, 0.5462, 0.8547, 0.5298, 0.5782],
          [0.8879, 0.4451, 0.8186, 0.8094, 0.0861],
          [0.6148, 0.6860, 0.2304, 0.6595, 0.0728],
          [0.6197, 0.9000, 0.3588, 0.7454, 0.5488]],

         [[0.0797, 0.8066, 0.6659, 0.2382, 0.9373],
          [0.6400, 0.2330, 0.8380, 0.3242, 0.7250],
          [0.7332, 0.5910, 0.7442, 0.7676, 0.1817],
  

In [16]:
#stack 维度保持一致，维度扩充，增加维度
import torch
a=torch.rand(8,5)
b=torch.rand(8,5)
c=torch.stack([a,b],dim=0)
print(c)
torch.stack([a,b],dim=0).shape #一个老师教的两个班的学生成绩表，合并到一个成绩表中

tensor([[[0.4823, 0.3021, 0.3833, 0.9491, 0.9762],
         [0.0029, 0.0559, 0.6477, 0.7873, 0.0850],
         [0.8616, 0.3845, 0.7781, 0.1837, 0.4403],
         [0.5376, 0.6035, 0.7013, 0.1370, 0.0625],
         [0.8679, 0.1644, 0.8413, 0.4864, 0.5765],
         [0.8317, 0.3722, 0.8359, 0.8913, 0.6383],
         [0.7637, 0.3000, 0.9187, 0.3480, 0.6082],
         [0.4211, 0.9321, 0.3858, 0.6315, 0.7790]],

        [[0.6224, 0.8218, 0.1311, 0.0877, 0.1001],
         [0.6150, 0.6710, 0.8390, 0.4058, 0.0130],
         [0.9613, 0.5571, 0.8948, 0.2685, 0.2851],
         [0.0293, 0.6476, 0.4888, 0.7876, 0.4461],
         [0.2546, 0.3150, 0.9129, 0.7060, 0.9971],
         [0.4840, 0.4050, 0.0272, 0.4364, 0.8448],
         [0.3037, 0.3943, 0.5825, 0.3245, 0.5507],
         [0.9810, 0.4262, 0.0248, 0.9844, 0.9174]]])


torch.Size([2, 8, 5])

In [22]:
#split 按长度拆分
import torch
a=torch.rand(5,8)
b=torch.rand(5,8)
c=torch.stack([a,b],dim=0)
print(c.shape)
a1,b1=c.split(1,dim=0) #2/1=2  按每个长度是一，可以拆分成两个
print(a1,"\n",b1)

torch.Size([2, 5, 8])
tensor([[[0.9940, 0.4607, 0.2119, 0.7613, 0.5081, 0.2077, 0.2987, 0.9229],
         [0.5870, 0.7044, 0.2786, 0.4516, 0.4387, 0.7552, 0.9135, 0.0653],
         [0.3150, 0.6826, 0.7681, 0.6181, 0.0381, 0.8587, 0.8496, 0.7213],
         [0.2833, 0.7976, 0.1758, 0.9952, 0.2523, 0.3917, 0.6512, 0.6324],
         [0.1687, 0.7694, 0.4649, 0.1244, 0.0928, 0.1633, 0.8867, 0.4347]]]) 
 tensor([[[0.8982, 0.3689, 0.1801, 0.5796, 0.0436, 0.4598, 0.8390, 0.6713],
         [0.8287, 0.4457, 0.5547, 0.3886, 0.1396, 0.0892, 0.2051, 0.9038],
         [0.7268, 0.0299, 0.0377, 0.5677, 0.7469, 0.5716, 0.4270, 0.3570],
         [0.0746, 0.4048, 0.9864, 0.7815, 0.7485, 0.8738, 0.9282, 0.7575],
         [0.7129, 0.4966, 0.2879, 0.6056, 0.8699, 0.1762, 0.3343, 0.5610]]])


In [26]:
#split 按长度拆分 example
import torch
a=torch.rand(3,8,5)
b=torch.rand(2,8,5)
c=torch.cat([a,b],dim=0)
print(c.shape)
a1,b1=c.split([3,2],dim=0) #第一个三个长度，第二个两个长度
print(a1)
print(b1)

torch.Size([5, 8, 5])
tensor([[[0.2392, 0.5143, 0.8923, 0.2502, 0.9004],
         [0.5918, 0.8644, 0.1199, 0.9510, 0.0578],
         [0.5649, 0.5424, 0.7356, 0.9583, 0.1355],
         [0.5010, 0.4048, 0.4950, 0.1104, 0.4263],
         [0.7838, 0.4446, 0.6066, 0.1597, 0.7065],
         [0.4212, 0.6377, 0.0630, 0.9461, 0.5079],
         [0.0502, 0.6275, 0.6285, 0.6174, 0.3166],
         [0.1264, 0.8271, 0.8270, 0.4490, 0.6118]],

        [[0.0634, 0.0173, 0.2643, 0.3082, 0.9722],
         [0.8331, 0.7813, 0.7197, 0.4090, 0.0637],
         [0.0636, 0.1418, 0.3695, 0.0406, 0.2113],
         [0.3480, 0.5235, 0.8780, 0.7486, 0.5650],
         [0.2679, 0.6231, 0.1687, 0.0963, 0.7416],
         [0.3133, 0.0621, 0.4648, 0.8228, 0.6402],
         [0.9445, 0.3377, 0.1242, 0.4437, 0.7709],
         [0.6991, 0.0925, 0.7673, 0.0641, 0.2245]],

        [[0.7522, 0.7973, 0.4490, 0.2122, 0.0633],
         [0.8022, 0.7289, 0.1120, 0.9087, 0.1205],
         [0.2678, 0.4025, 0.6545, 0.4553, 0.7293],
     

In [29]:
#chunk 按num拆分
import torch
a=torch.rand(5,8)
b=torch.rand(5,8)
c=torch.stack([a,b],dim=0)
print(c.shape)
c1,d1=c.chunk(2,dim=0) #拆分两个
print(c1)
print(d1)

torch.Size([2, 5, 8])
tensor([[[0.2109, 0.0377, 0.5452, 0.4143, 0.7440, 0.3364, 0.5272, 0.7113],
         [0.0843, 0.0905, 0.5544, 0.7250, 0.2683, 0.6310, 0.7588, 0.6793],
         [0.0616, 0.0831, 0.5537, 0.0348, 0.2456, 0.2841, 0.2198, 0.5546],
         [0.7413, 0.8828, 0.6623, 0.0828, 0.2493, 0.3265, 0.8743, 0.6573],
         [0.3511, 0.5204, 0.1065, 0.9266, 0.8364, 0.6503, 0.5349, 0.8263]]])
tensor([[[0.2094, 0.9912, 0.4036, 0.1616, 0.5434, 0.4757, 0.4793, 0.6269],
         [0.2352, 0.9915, 0.8868, 0.6069, 0.5586, 0.4474, 0.2578, 0.6309],
         [0.1446, 0.7608, 0.5209, 0.7685, 0.5615, 0.4130, 0.8011, 0.3530],
         [0.5134, 0.6362, 0.2604, 0.7004, 0.9405, 0.7551, 0.5199, 0.7807],
         [0.9592, 0.1130, 0.6061, 0.6226, 0.9280, 0.2857, 0.3503, 0.3971]]])
