In [1]:
import torch
from torch.nn import functional as F
a=torch.tensor([0.1440,0.5349,0.7022],requires_grad=True)
a

tensor([0.1440, 0.5349, 0.7022], requires_grad=True)

In [2]:
p=F.softmax(a,dim=0)
p


tensor([0.2366, 0.3498, 0.4135], grad_fn=<SoftmaxBackward>)

In [3]:
p.backward(a)
a.grad

tensor([-0.0870,  0.0082,  0.0788])

In [4]:
p=F.softmax(a,dim=0)
torch.autograd.grad(p[0],[a],retain_graph=True)


(tensor([ 0.1806, -0.0828, -0.0979]),)

In [5]:
torch.autograd.grad(p[1],[a],retain_graph=True)

(tensor([-0.0828,  0.2274, -0.1447]),)

In [6]:
torch.autograd.grad(p[2],[a],retain_graph=True)

(tensor([-0.0979, -0.1447,  0.2425]),)