In [1]:
import torch
a=torch.full([8],1.)
b=a.view(2,4)
c=a.view(2,2,2)


In [2]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [6]:
print(a)
print(a.shape)
a.norm(1)#每个元素的绝对值加和

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([8])


tensor(8.)

In [7]:
print(b)
print(b.shape)
b.norm(1)#1范式每个元素的绝对值加和 这里不是维度

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([2, 4])


tensor(8.)

In [8]:
print(c)
print(c.shape)
b.norm(1)#1范式每个元素的绝对值加和 这里不是维度

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([2, 2, 2])


tensor(8.)

In [10]:
print(a)
print(a.shape)
a.norm(2)#2范式每个元素的平方和，再开方




tensor([1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([8])


tensor(2.8284)

In [11]:
print(b)
print(b.shape)
b.norm(2)#2范式每个元素的平方和，再开方


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([2, 4])


tensor(2.8284)

In [13]:
print(c)
print(c.shape)
c.norm(2)#2范式每个元素的平方和，再开方

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([2, 2, 2])


tensor(2.8284)

In [16]:
#求固定维度的范式
print(b)
print(b.shape)
b.norm(1,dim=1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([2, 4])


tensor([4., 4.])

In [17]:
print(b)
print(b.shape)
b.norm(2,dim=1)#每一行的元素平方和相加再开方

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([2, 4])


tensor([2., 2.])

In [19]:
print(c)
c.norm(1,dim=1)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


tensor([[2., 2.],
        [2., 2.]])

In [21]:
print(c)
print(c.shape)
c.norm(2,dim=0) #第一组的每个元素的平方跟第二组每个元素的平方相加再开方

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([2, 2, 2])


tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [23]:
# mean sum min max prod
a=torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [24]:
a.min(),a.max(),a.mean(),a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [25]:
a.sum()

tensor(28.)

In [26]:
a.argmax()#返回最大值的索引 不指定维度，默认打平再取索引

tensor(7)

In [27]:
a.argmin() #返回最小值的索引

tensor(0)

In [30]:
#指定维度，返回索引
a=torch.rand(4,10)
a

tensor([[0.7405, 0.1599, 0.2236, 0.8077, 0.3509, 0.7943, 0.2506, 0.3646, 0.4158,
         0.2230],
        [0.1198, 0.8512, 0.0733, 0.8265, 0.3936, 0.2234, 0.3560, 0.3017, 0.1274,
         0.1164],
        [0.0185, 0.1926, 0.9043, 0.3161, 0.4838, 0.7249, 0.7514, 0.3679, 0.0801,
         0.1253],
        [0.0218, 0.9629, 0.0718, 0.4047, 0.7910, 0.0189, 0.5617, 0.7086, 0.3235,
         0.8325]])

In [31]:
a[0]

tensor([0.7405, 0.1599, 0.2236, 0.8077, 0.3509, 0.7943, 0.2506, 0.3646, 0.4158,
        0.2230])

In [32]:
a.argmax()

tensor(31)

In [34]:
print(a.shape)
a.argmax(dim=1)#4组 每组元素的10个值中最大的索引显示出来

torch.Size([4, 10])


tensor([3, 1, 2, 1])

In [35]:
#dim，keepdim 配合函数应用
a

tensor([[0.7405, 0.1599, 0.2236, 0.8077, 0.3509, 0.7943, 0.2506, 0.3646, 0.4158,
         0.2230],
        [0.1198, 0.8512, 0.0733, 0.8265, 0.3936, 0.2234, 0.3560, 0.3017, 0.1274,
         0.1164],
        [0.0185, 0.1926, 0.9043, 0.3161, 0.4838, 0.7249, 0.7514, 0.3679, 0.0801,
         0.1253],
        [0.0218, 0.9629, 0.0718, 0.4047, 0.7910, 0.0189, 0.5617, 0.7086, 0.3235,
         0.8325]])

In [36]:
print(a.shape)
a.max(dim=1)

torch.Size([4, 10])


torch.return_types.max(
values=tensor([0.8077, 0.8512, 0.9043, 0.9629]),
indices=tensor([3, 1, 2, 1]))

In [37]:
a.argmax(dim=1)

tensor([3, 1, 2, 1])

In [38]:
a.max(dim=1,keepdim=True)

torch.return_types.max(
values=tensor([[0.8077],
        [0.8512],
        [0.9043],
        [0.9629]]),
indices=tensor([[3],
        [1],
        [2],
        [1]]))

In [39]:
a.argmax(dim=1,keepdim=True)

tensor([[3],
        [1],
        [2],
        [1]])

In [40]:
#返回更多的top-k数据
a

tensor([[0.7405, 0.1599, 0.2236, 0.8077, 0.3509, 0.7943, 0.2506, 0.3646, 0.4158,
         0.2230],
        [0.1198, 0.8512, 0.0733, 0.8265, 0.3936, 0.2234, 0.3560, 0.3017, 0.1274,
         0.1164],
        [0.0185, 0.1926, 0.9043, 0.3161, 0.4838, 0.7249, 0.7514, 0.3679, 0.0801,
         0.1253],
        [0.0218, 0.9629, 0.0718, 0.4047, 0.7910, 0.0189, 0.5617, 0.7086, 0.3235,
         0.8325]])

In [45]:
a.topk(2)#不指定取最后一个维度

torch.return_types.topk(
values=tensor([[0.8077, 0.7943],
        [0.8512, 0.8265],
        [0.9043, 0.7514],
        [0.9629, 0.8325]]),
indices=tensor([[3, 5],
        [1, 3],
        [2, 6],
        [1, 9]]))

In [46]:
a.topk(2,dim=1) #前两个最大的

torch.return_types.topk(
values=tensor([[0.8077, 0.7943],
        [0.8512, 0.8265],
        [0.9043, 0.7514],
        [0.9629, 0.8325]]),
indices=tensor([[3, 5],
        [1, 3],
        [2, 6],
        [1, 9]]))

In [47]:
a.topk(2,dim=1,largest=False)#取最小的两个值

torch.return_types.topk(
values=tensor([[0.1599, 0.2230],
        [0.0733, 0.1164],
        [0.0185, 0.0801],
        [0.0189, 0.0218]]),
indices=tensor([[1, 9],
        [2, 9],
        [0, 8],
        [5, 0]]))

In [48]:
a.kthvalue(8,dim=1) #取第二维度中的第八个小的数以及索引

torch.return_types.kthvalue(
values=tensor([0.7405, 0.3936, 0.7249, 0.7910]),
indices=tensor([0, 4, 5, 4]))

In [49]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([0.2236, 0.1198, 0.1253, 0.0718]),
indices=tensor([2, 0, 9, 2]))

In [50]:
a.kthvalue(3,dim=1)

torch.return_types.kthvalue(
values=tensor([0.2236, 0.1198, 0.1253, 0.0718]),
indices=tensor([2, 0, 9, 2]))

In [51]:
#比较运算操作 compare
a>0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [52]:
torch.gt(a,2) #a大于2的

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [53]:
a!=0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [54]:
a=torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [55]:
b=torch.eye(2,2)
b

tensor([[1., 0.],
        [0., 1.]])

In [56]:
torch.eq(a,b)

tensor([[ True, False],
        [False,  True]])

In [57]:
torch.equal(a,b)

False