In [1]:
#type chack
import torch
a=torch.randn(2,3) #二维的tensor张量，随机正态分布 N（0，1）
a

tensor([[-1.2684, -0.8986,  1.1558],
        [ 0.2176, -0.6036, -0.2610]])

In [2]:
a.type() #返回基本数据类型的详细信息

'torch.FloatTensor'

In [3]:
type(a) #返回基本数据类型

torch.Tensor

In [4]:
isinstance(a,torch.FloatTensor)

True

In [5]:
isinstance(a,torch.cuda.FloatTensor)

False

In [6]:
a=a.cuda() #将数据搬运到gpu上 返回索引
isinstance(a,torch.cuda.FloatTensor)

AssertionError: Torch not compiled with CUDA enabled

In [8]:
#张量 标量 维度之间的表示与认识
import torch
a=torch.tensor(1.) #torch.FloatTensor
b=torch.tensor(1.3) #orch.FloatTensor
c=torch.tensor(1) # torch.LongTensor
print(a.type(),b.type(),c.type())
print(a,b,c)#dim=0

torch.FloatTensor torch.FloatTensor torch.LongTensor
tensor(1.) tensor(1.3000) tensor(1)


In [9]:
#Dim=0
import torch
a=torch.tensor(2.2)
print(a)
print(a.shape)  # 显示全局维度信息 
print(a.size()) # 显示该维度的长度
len(a.shape)

tensor(2.2000)
torch.Size([])
torch.Size([])


0

In [10]:
#Dim=1
import torch
a=torch.tensor([1.1])
print(a)
print(a.shape)  # 显示全局维度信息 
print(a.size()) # 显示该维度的长度
print(len(a.shape))
print("\n")
b=torch.tensor([1.1,2.2,3.3])
print(b.shape)  # 显示全局维度信息 数字表示该维度下向量的长度 ,几个数字表示几维数据
print(b.size()) # 参数不指定则显示全局维度信息
print(len(b.shape))
print("\n")



tensor([1.1000])
torch.Size([1])
torch.Size([1])
1


torch.Size([3])
torch.Size([3])
1




In [25]:
#Dim=1 FloatTensor()应用 ones应用 list迁移到tensor
import torch
import numpy as np
a=torch.Tensor(1)
b=torch.FloatTensor(1) #生成维度为1，向量长度为1的 tensor
c=torch.FloatTensor(2) #生成维度为1，向量长度为2的 tensor
print(a)
print(b)
print(c)
print("\n")

d=torch.ones(2)
print(d)
print(d.shape)
print("\n")

data=np.ones(2) #生成维度为1，list数据每个元素都是1的串|数组
print(data)
e=torch.from_numpy(data) #将numpy数据转换成tensor默认数据类型
e

tensor([-4.1633e+21])
tensor([-4.1633e+21])
tensor([1.0000, 1.0000])


tensor([1., 1.])
torch.Size([2])


[1. 1.]


tensor([1., 1.], dtype=torch.float64)

In [30]:
#dim=2
import torch
a=torch.randn(2,3)
print(a,a.shape,a.size()) #torch.Size([2, 3]) 两个数字表示二维数据，每一维的长度分别是2和3

print(a.size(0)) #0维度上的向量长度是2
print(a.size(1)) #1维度上的向量长度是3

print(a.shape[1])




tensor([[ 0.7577,  2.2654,  0.5147],
        [-0.4758,  2.5119,  0.9388]]) torch.Size([2, 3]) torch.Size([2, 3])
2
3
3


In [47]:
#dim=3
import torch
a=torch.rand(3,2,4)
print(a)
print(a.shape)
print(a[0])
list(a.shape)



tensor([[[0.2865, 0.2976, 0.0274, 0.0152],
         [0.3216, 0.6000, 0.2234, 0.0638]],

        [[0.1820, 0.6870, 0.7096, 0.8861],
         [0.8449, 0.7022, 0.2568, 0.6619]],

        [[0.1212, 0.9075, 0.9556, 0.0444],
         [0.6315, 0.3709, 0.5806, 0.5285]]])
torch.Size([3, 2, 4])
tensor([[0.2865, 0.2976, 0.0274, 0.0152],
        [0.3216, 0.6000, 0.2234, 0.0638]])


[3, 2, 4]

In [67]:
#dim=3 vs dim=4  numle函数（） dim（）
a=torch.rand(3,2,4)
print(a,"\n")
b=torch.rand(2,3,2,4)
print(b,"\n\n",b.shape)

c=torch.tensor(1)

d=torch.tensor([1])

print(a.numel(),b.numel())
print(a.dim(),b.dim(),c.dim(),d.dim())




tensor([[[0.6843, 0.2932, 0.7865, 0.4036],
         [0.3674, 0.6459, 0.7272, 0.0952]],

        [[0.1063, 0.3525, 0.5847, 0.7114],
         [0.3845, 0.4054, 0.6750, 0.3152]],

        [[0.9955, 0.0046, 0.6979, 0.8180],
         [0.9545, 0.5063, 0.3121, 0.7808]]]) 

tensor([[[[0.8392, 0.0568, 0.7579, 0.3329],
          [0.7765, 0.1720, 0.1017, 0.5132]],

         [[0.9378, 0.5783, 0.7810, 0.0074],
          [0.3458, 0.4591, 0.6081, 0.2416]],

         [[0.7068, 0.1938, 0.6932, 0.1228],
          [0.3639, 0.5531, 0.3296, 0.7285]]],


        [[[0.5022, 0.5182, 0.4624, 0.9228],
          [0.8436, 0.1003, 0.1673, 0.8095]],

         [[0.2983, 0.3930, 0.4544, 0.1026],
          [0.8621, 0.8905, 0.1019, 0.4213]],

         [[0.9177, 0.0451, 0.6906, 0.5293],
          [0.7536, 0.3593, 0.6521, 0.4029]]]]) 

 torch.Size([2, 3, 2, 4])
24 48
3 4 0 1
